SUPER_USERS:
- admin
FEATURE_SUPERUSERS_FULL_ACCESS: true
BITTORRENT_FILENAME_PEPPER: 0ee18f90-5b6d-42d2-ab5e-ec9fcd846272
BUILDLOGS_REDIS:
  host: ___CONFIGURATION___
  port: ___CONFIGURATION___
DB_URI: ___CONFIGURATION___
DATABASE_SECRET_KEY: '30060361640793187613697366923211113205676925445650250274752125083971638376224'
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
  default:
  - RadosGWStorage 
  - hostname: ___CONFIGURATION___
    access_key: ___CONFIGURATION___
    secret_key: ___CONFIGURATION___
    bucket_name: ___CONFIGURATION___
    is_secure: true
    storage_path: /data
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
- default
ENTERPRISE_LOGO_URL: /static/img/quay-horizontal-color.svg
EXTERNAL_TLS_TERMINATION: true
ALLOW_WITHOUT_STRICT_LOGGING: true
FEATURE_ANONYMOUS_ACCESS: false
FEATURE_APP_REGISTRY: false
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_GARBAGE_COLLECTION: false
FEATURE_MAILING: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_REPO_MIRROR: false
FEATURE_REQUIRE_TEAM_INVITE: true
FEATURE_EXTENDED_REPOSITORY_NAMES: false
CREATE_PRIVATE_REPO_ON_PUSH: true
CREATE_NAMESPACE_ON_PUSH: false
FEATURE_SECURITY_NOTIFICATIONS: false
FEATURE_SECURITY_SCANNER: false
FEATURE_USERNAME_CONFIRMATION: false
FEATURE_SUPERUSERS_ORG_CREATION_ONLY: true
FEATURE_USER_METADATA: false
FEATURE_USER_LAST_ACCESSED: true
FEATURE_PROXY_CACHE: true
LOG_ARCHIVE_LOCATION: default
PREFERRED_URL_SCHEME: http
REGISTRY_TITLE: STELAR KLMS Image Registry
REGISTRY_TITLE_SHORT: STELAR Registry
REPO_MIRROR_SERVER_HOSTNAME: null
REPO_MIRROR_TLS_VERIFY: false
SERVER_HOSTNAME: ___CONFIGURATION___
SETUP_COMPLETE: true
SIGNING_ENGINE: gpg2
TAG_EXPIRATION_OPTIONS:
- 0s
- 1d
- 1w
- 2w
- 4w
TEAM_RESYNC_STALE_TIME: 60m
TESTING: false
USERFILES_LOCATION: default
USERFILES_PATH: userfiles/
USER_EVENTS_REDIS:
  host: ___CONFIGURATION___
  port: ___CONFIGURATION___
USE_CDN: false
FEATURE_QUOTA_MANAGEMENT: false
BROWSER_API_CALLS_XHR_ONLY: false
CORS_ORIGIN:
  - "https://stage.foo.redhat.com:1337"
  - "http://localhost:9000"
FEATURE_UI_V2: true
AUTHENTICATION_TYPE: OIDC
OIDC_LOGIN_CONFIG:
  DEBUGLOG: true
  CLIENT_ID: ___CONFIGURATION___
  CLIENT_SECRET: ___CONFIGURATION___
  OIDC_SERVER: ___CONFIGURATION___
  SERVICE_NAME: STELAR SSO
  PREFERRED_USERNAME_CLAIM_NAME: preferred_username
  VERIFIED_EMAIL_CLAIM_NAME: email
  OIDC_DISABLE_USER_ENDPOINT: false
  PREFERRED_GROUP_CLAIM_NAME: groups
  LOGIN_SCOPES: [ 'openid' ] 
FEATURE_TEAM_SYNCING: true
FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false