#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE "$SUPERSET_USER" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$SUPERSET_PASSWORD';
    CREATE DATABASE "$SUPERSET_DB" OWNER "$SUPERSET_USER" ENCODING 'utf-8';
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$SUPERSET_DB" <<-EOSQL
    CREATE EXTENSION postgis;
EOSQL

